app/appointment/urls.py
from django.urls import path

from . import views

app_name = 'appointment'

urlpatterns = [
    # Записи
    path('', views.AppointmentListView.as_view(), name='list'),
    path('create/', views.AppointmentCreateView.as_view(), name='create'),
    path('<int:pk>/', views.AppointmentDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.AppointmentUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.AppointmentDeleteView.as_view(), name='delete'),
    path('<int:pk>/review', views.AppointmentReviewView.as_view(), name='review'),
]

app/beautycrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about, service, OrderView

from profile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/services/', include('service.urls')),
    path('dashboard/appointment/', include('appointment.urls')),
    path('dashboard/payment/', include('payment.urls')),
    path('dashboard/', include('profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('service/', service, name='service'),
    path('order/', OrderView.as_view(), name='order'),
    path('log-in/', views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    # path('', views.dashboard, name='index'),
    path('', views.DashboardView.as_view(), name='index'),
]

app/payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    # Выплаты
    path('', views.PaymentListView.as_view(), name='list'),
    path('create/', views.PaymentCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.PaymentUpdateView.as_view(), name='update'),
]

app/profile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    
    # Client
    path('clients/', views.ClientListView.as_view(), name='client_list'),
    path('clients/create/', views.ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),
    
    # Worker
    path('workers/', views.WorkerListView.as_view(), name='worker_list'),
    path('workers/create/', views.WorkerCreateView.as_view(), name='worker_create'),
    path('workers/<int:pk>/update/', views.WorkerUpdateView.as_view(), name='worker_update'),
    path('workers/<int:pk>/delete/', views.WorkerDeleteView.as_view(), name='worker_delete'),
    
    # Position
    path('workers/position/', views.PositionListView.as_view(), name='position_list'),
    path('workers/position/create/', views.PositionCreateView.as_view(), name='position_create'),
    path('workers/position/<int:pk>/update/', views.PositionUpdateView.as_view(), name='position_update'),
    path('workers/position/<int:pk>/delete/', views.PositionDeleteView.as_view(), name='position_delete'),
    
    # Account
    path('myaccount/', views.myaccount, name='myaccount'),
    path('update_myaccount/<int:pk>', views.MyAccountUpdateView.as_view(), name='update_myaccount'),
    path('sign-up/', views.signup, name='signup'),
]

app/service/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    # Услуги
    path('', views.ServiceListView.as_view(), name='list'),
    path('create/', views.ServiceCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ServiceDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.ServiceUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.ServiceDeleteView.as_view(), name='delete'),
    # Категории услуг
    path('category/', views.ServiceCategoryListView.as_view(), name='category_list'),
    path('category/create/', views.ServiceCategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.ServiceCategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.ServiceCategoryDeleteView.as_view(), name='category_delete'),
]

app/core/models.py
from django.db import models

# Create your models here.

app/core/forms.py
from django import forms
from beautycrm.constants import FORMS
from appointment.models import Appointment
from service.models import Service
from profile.models import WorkerProfile

class OrderNoAuthForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        required=False,
        widget=forms.TextInput(attrs={'class': FORMS['FIELD_CLASS']})
    )
    phone = forms.CharField(
        max_length=20,
        required=False,
        widget=forms.TextInput(attrs={'class': FORMS['FIELD_CLASS']})
    )
    email = forms.EmailField(
        required=False,
        widget=forms.EmailInput(attrs={'class': FORMS['FIELD_CLASS']})
    )
    worker = forms.ModelChoiceField(
        queryset=WorkerProfile.objects.all(),
        widget=forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
    )
    service = forms.ModelChoiceField(
        queryset=Service.objects.all(),
        widget=forms.Select(attrs={'class': FORMS['FIELD_CLASS']})
    )
    start_time = forms.DateTimeField(widget=forms.DateTimeInput(attrs={
        'type': 'datetime-local',
        'class': FORMS['FIELD_CLASS']
    }))
    notes = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'class': FORMS['FIELD_CLASS']}),
        required=False
    )

class OrderForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            'client',
            'worker',
            'service',
            'start_time',
            'status',
            'notes',
        ]
        widgets = {
            'client': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'worker': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'service': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'start_time': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'class': FORMS['FIELD_CLASS']
            }),
            'status': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'notes': forms.Textarea(attrs={'rows': 3, 'class': FORMS['FIELD_CLASS']}),
        }

app/core/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from unidecode import unidecode
from utils.messager import send_custom_email
from core.forms import OrderForm, OrderNoAuthForm
from appointment.models import Appointment, Review
from service.models import Service, ServiceCategory
from django.views.generic.edit import FormView
from profile.models import ClientProfile
from django.contrib.auth.models import User
from django.utils.crypto import get_random_string

def index(request):
    # Получаем все активные категории
    categories = ServiceCategory.objects.filter(is_active=True)
    
    # Получаем список отзывов
    reviews = Review.objects.all()
    
    # Контекст с категориями и их услугами
    context = {
        'service_categories': categories,
        'reviews': reviews,
    }
        
    return render(request, 'core/index.html', context)

def about(request):
    return render(request, 'core/about.html')

def service(request):
    # return render(request, 'core/index.html')
    # Получаем все активные категории
    categories = ServiceCategory.objects.filter(is_active=True)
    
    # Контекст с категориями и их услугами
    context = {
        'service_categories': categories,
    }
        
    return render(request, 'core/service.html', context)


class OrderView(FormView):
    # model = Appointment
    form_class = OrderNoAuthForm
    template_name = 'core/order.html'
    success_url = reverse_lazy('dashboard:index')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        service_id = self.request.GET.get('service')
        service = Service.objects.filter(id=service_id).first()
        context['service'] = service
        # send_custom_email(
        #     subject='Запись подтверждена',
        #     message='Ваша запись в салон успешно подтверждена.',
        #     recipient_list=['mail.websofter@gmail.com']
        # )
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        service_id = self.request.GET.get('service')
        if service_id:
            kwargs['initial'] = kwargs.get('initial', {})
            kwargs['initial']['service'] = service_id
        return kwargs

    def form_valid(self, form):
        user = self.request.user if self.request.user.is_authenticated else None
        # 2. Обновляем данные пользователя из очищенных данных формы
        if not user:
            username = unidecode(form.cleaned_data['name'].lower())
            password = get_random_string(length=6)
            email = form.cleaned_data['email']
            user = User.objects.create_user(
                username=username,
                password=password,
                first_name=form.cleaned_data['name'],
                # last_name=form.cleaned_data['last_name'],
                email=email,
            )
            if email:
                send_custom_email(
                    subject='Создана учетная запись',
                    message=f'Ваша аккаунт успешно создан: логин: {username}, пароль: {password}',
                    recipient_list=[email]
                )
        # Создаем профиль
        client_profile, created = ClientProfile.objects.get_or_create(
            user=user,
            defaults={
                'phone': form.cleaned_data.get('phone'),
            }
        )
        # Создаем запись на прием
        start_time = form.cleaned_data.get('start_time')
        worker = form.cleaned_data.get('worker')
        service = form.cleaned_data.get('service')
        appointment = Appointment.objects.create(
            client=client_profile,
            service=service,
            worker=worker,
            start_time=start_time,
            status='pending',
            notes=form.cleaned_data.get('notes', '')
        )
        if user.email:
            send_custom_email(
                subject='Вы записаны в салон красоты',
                message=f'Вы успешно записаны на процедулу {service.name}. Время: {start_time}',
                recipient_list=[user.email]
            )
        if worker.user.email:
            send_custom_email(
                subject='К вам записался клиент',
                message=f'Клиент записан на процедуру {service.name}. Время: {start_time}',
                recipient_list=[worker.user.email]
            )
        return super().form_valid(form)

app/core/templates/core/partials/footer.html
<footer class="py-8 text-center bg-gray-200">
    <p class="text-xs text-gray-700">Copyright (c) {% now "Y" %} - Beauty CRM</p>
</footer>

app/core/templates/core/partials/nav.html
{% load static %}

<nav class="py-6 px-6 flex justify-between bg-fuchsia-500">
    <a href="/" class="flex items-center space-x-3 rtl:space-x-reverse">
        <img src="{% static 'images/logo.svg' %}" class="h-8" alt="Beauty CRM" />
        <span class="self-center text-2xl font-semibold whitespace-nowrap dark:text-white">Beauty CRM</span>
    </a>
    <div class="space-x-4">
        <a href="{% url 'index' %}" class="text-white">Главная</a>
        <a href="{% url 'about' %}" class="text-white">О студии</a>
        <a href="{% url 'service' %}" class="text-white">Записаться</a>
        {% if request.user.is_authenticated %}
            <a href="{% url 'dashboard:index' %}" class="py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Панель</a>

            {% if request.user.is_superuser %}
                <a href="{% url 'payment:list' %}" class="py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Зарплаты</a>
            {% endif %}
            {% if request.user.is_superuser or profile_type == 'worker' %}
                <a href="{% url 'appointment:list' %}" class="py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Записи</a>
            {% endif %}
            {% if request.user.is_superuser %}
                <div class="relative group inline-block">
                    <a href="{% url 'profile:client_list' %}" class="py-4 px-6 bg-fuchsia-600 rounded-xl text-white inline-flex items-center">
                        Соцфонд
                        <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7"/>
                        </svg>
                    </a>
                    <div class="absolute left-0 mt-2 w-48 bg-white rounded-md shadow-lg opacity-0 group-hover:opacity-100 transition-opacity z-10">
                        <a href="{% url 'profile:client_list' %}" class="block px-4 py-2 text-gray-800 hover:bg-fuchsia-100">Клиенты</a>
                        <a href="{% url 'profile:worker_list' %}" class="block px-4 py-2 text-gray-800 hover:bg-fuchsia-100">Сотрудники</a>
                        <a href="{% url 'profile:position_list' %}" class="block px-4 py-2 text-gray-800 hover:bg-fuchsia-100">Специализации</a>
                    </div>
                </div>
                <div class="relative group inline-block">
                    <a href="{% url 'services:list' %}" class="py-4 px-6 bg-fuchsia-600 rounded-xl text-white inline-flex items-center">
                        Услуги
                        <svg class="w-4 h-4 ml-2" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M19 9l-7 7-7-7"/>
                        </svg>
                    </a>
                    <div class="absolute left-0 mt-2 w-48 bg-white rounded-md shadow-lg opacity-0 group-hover:opacity-100 transition-opacity z-10">
                        <a href="{% url 'services:list' %}" class="block px-4 py-2 text-gray-800 hover:bg-fuchsia-100">Услуги</a>
                        <a href="{% url 'services:category_list' %}" class="block px-4 py-2 text-gray-800 hover:bg-fuchsia-100">Категории</a>
                    </div>
                </div>
            {% endif %}
            <a href="{% url 'profile:myaccount' %}" class="py-4 px-6 bg-fuchsia-800 rounded-xl text-white">Мой аккаунт</a>
        {% else %}
            <a href="{% url 'login' %}" class="py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Вход</a>
            <a href="{% url 'profile:signup' %}" class="py-4 px-6 bg-fuchsia-300 rounded-xl text-white">Регистрация</a>
        {% endif %}
    </div>
</nav>