app/appointment/urls.py
from django.urls import path

from . import views

app_name = 'appointment'

urlpatterns = [
    # Записи
    path('', views.AppointmentListView.as_view(), name='list'),
    path('create/', views.AppointmentCreateView.as_view(), name='create'),
    path('<int:pk>/', views.AppointmentDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.AppointmentUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.AppointmentDeleteView.as_view(), name='delete'),
    path('<int:pk>/review', views.AppointmentReviewView.as_view(), name='review'),
]

app/beautycrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about, service, OrderView

from profile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/services/', include('service.urls')),
    path('dashboard/appointment/', include('appointment.urls')),
    path('dashboard/payment/', include('payment.urls')),
    path('dashboard/', include('profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('service/', service, name='service'),
    path('order/', OrderView.as_view(), name='order'),
    path('log-in/', views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/dashboard/urls.py
from django.urls import path

from . import views

app_name = 'dashboard'

urlpatterns = [
    # path('', views.dashboard, name='index'),
    path('', views.DashboardView.as_view(), name='index'),
]

app/payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    # Выплаты
    path('', views.PaymentListView.as_view(), name='list'),
    path('create/', views.PaymentCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.PaymentUpdateView.as_view(), name='update'),
]

app/appointment/models.py
from django.db import models
from django.utils import timezone

from profile.models import ClientProfile
from profile.models import WorkerProfile
from service.models import Service

# Create your models here.

class Appointment(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Ожидает подтверждения'),
        ('confirmed', 'Подтверждена'),
        ('completed', 'Завершена'),
        ('cancelled', 'Отменена'),
    ]

    client = models.ForeignKey(ClientProfile, on_delete=models.CASCADE, related_name='appointments')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='appointments', null=True)
    worker = models.ForeignKey(WorkerProfile, on_delete=models.CASCADE, related_name='appointments', null=True)

    start_time = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-created_at', ]

    def __str__(self):
        return f"{self.client} — {self.service}"


class Review(models.Model):
    RATING_CHOICES = [
        (1, '1 звезда'),
        (2, '2 звезды'),
        (3, '3 звезды'), 
        (4, '4 звезды'),
        (5, '5 звезд'),
    ]

    client = models.ForeignKey(ClientProfile, on_delete=models.CASCADE, related_name='reviews')
    worker = models.ForeignKey(WorkerProfile, on_delete=models.CASCADE, related_name='reviews')
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='reviews')  # Исправлено: apointment -> appointment
    rating = models.IntegerField(choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['client'], name='idx_review_client'),
            models.Index(fields=['worker'], name='idx_review_worker'),
            models.Index(fields=['appointment'], name='idx_review_appointment'),  # Исправлено: appointment
        ]
        # Рекомендуется добавить уникальное ограничение
        unique_together = ['client', 'appointment']

    def __str__(self):
        return f'Отзыв от {self.client} для {self.worker} - {self.rating} звезд'

app/appointment/forms.py
from django import forms
from beautycrm.constants import FORMS
from appointment.models import Appointment, Review

class AppointmentForm(forms.ModelForm):
    class Meta:
        model = Appointment
        fields = [
            'client',
            'worker',
            'service',
            'start_time',
            'status',
            'notes',
        ]
        widgets = {
            'client': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'worker': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'service': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'start_time': forms.DateTimeInput(attrs={
                'type': 'datetime-local',
                'class': FORMS['FIELD_CLASS']
            }),
            'status': forms.Select(attrs={'class': FORMS['FIELD_CLASS']}),
            'notes': forms.Textarea(attrs={'rows': 3, 'class': FORMS['FIELD_CLASS']}),
        }



class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('rating', 'comment')  # Только поля, которые заполняет пользователь
        widgets = {
            'rating': forms.Select(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
            'comment': forms.Textarea(attrs={
                'class': FORMS['FIELD_CLASS'],
                'rows': 4,
                'placeholder': 'Поделитесь своим отзывом о предоставленной услуге...'
            }),
        }

app/appointment/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView

from utils.messager import send_custom_email

from .forms import AppointmentForm, ReviewForm
from .models import Appointment, Review

class AppointmentListView(LoginRequiredMixin, ListView):
    model = Appointment
    
    def get_queryset(self):
        queryset = super(AppointmentListView, self).get_queryset()
        return queryset.all()

class AppointmentCreateView(LoginRequiredMixin, CreateView):
    model = Appointment
    form_class = AppointmentForm
    success_url = reverse_lazy('appointment:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['form'] = AppointmentForm()
        context['title'] = 'Добавить запись'

        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        
        return redirect(self.get_success_url())
class AppointmentDetailView(LoginRequiredMixin, DetailView):
    model = Appointment
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AppointmentForm()

        return context

    def get_queryset(self):
        queryset = super(AppointmentDetailView, self).get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))
    
class AppointmentDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        category = get_object_or_404(Appointment, pk=pk)
        # можно добавить проверку доступа
        category.delete()
        return redirect('appointment:list')

    def get(self, request, *args, **kwargs):
        # запретить или сделать редирект
        return redirect('appointment:list')

class AppointmentUpdateView(LoginRequiredMixin, UpdateView):
    model = Appointment
    form_class = AppointmentForm
    success_url = reverse_lazy('appointment:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменить запись'

        return context

    def form_valid(self, form):
        # Отправляем email после успешной валидации формы
        subject = 'Изменения в записи'
        message = f'''
        {form.instance.client}
        {form.instance.worker} 
        Статус: {form.instance.status} 
        Комментарий: {form.instance.notes} 
        Дата и время: {form.instance.start_time}
        '''
        send_custom_email(
            subject=subject,
            message=message,
            recipient_list=[form.instance.client.user.email]
        )
        
        # ВАЖНО: вызываем родительский метод form_valid
        return super().form_valid(form)

    def get_queryset(self):
        # Этот метод должен быть отдельным для фильтрации объектов
        queryset = super().get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))

    # def form_valid(self, form):

    #     subject = 'Изменения в записи'
    #     message = f'''
    #     Клиент: {form.instance.client}
    #     Мастер: {form.instance.worker} 
    #     Статус: {form.instance.status} 
    #     Дата и время: {form.instance.start_time}
    #     '''
    #     send_custom_email(
    #         subject=subject,
    #         message=message,
    #         recipient_list=[form.instance.client.user.email]
    #     )
        
    #     queryset = super(AppointmentUpdateView, self).get_queryset()
    #     return queryset.filter(pk=self.kwargs.get('pk'))





class AppointmentReviewView(LoginRequiredMixin, CreateView):
    model = Review  # Создаем Review, а не Appointment
    form_class = ReviewForm
    template_name = 'appointment/review_form.html'
    success_url = reverse_lazy('dashboard:index')

    def dispatch(self, request, *args, **kwargs):
        # Проверяем, что appointment существует
        self.appointment = get_object_or_404(Appointment, pk=self.kwargs['pk'])
        
        # Убедимся, что пользователь — клиент
        if not hasattr(request.user, 'clientprofile'):
            return redirect('dashboard:access_denied')
        
        # Проверяем, что это клиент этой записи
        if self.appointment.client != request.user.clientprofile:
            return redirect('dashboard:access_denied')
        
        return super().dispatch(request, *args, **kwargs)

    def get_initial(self):
        initial = super().get_initial()
        initial['client'] = self.appointment.client.pk  # Передаем ID
        initial['worker'] = self.appointment.worker.pk  # Передаем ID
        initial['appointment'] = self.appointment.pk    # Передаем ID
        return initial

    def form_valid(self, form):
        form.instance.client = self.appointment.client
        form.instance.worker = self.appointment.worker
        form.instance.appointment = self.appointment
        return super().form_valid(form)

app/appointment/templates/appointment/appointment_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">{{ title }}</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-4">
                <label class="block text-gray-700">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <p class="text-red-500 text-sm">{{ field.errors.0 }}</p>
                {% endif %}
                </div>
            {% endfor %}

            <button class="py-4 px-8 bg-fuchsia-500 text-white rounded-xl">Отправить</button>
        </form>
    </div>
{% endblock %}

app/appointment/templates/appointment/appointment_list.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{title}}</h1>

        <a href="{% url 'appointment:create' %}" class="inline-block py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Добавить</a>
    
        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Номер</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Клиент</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Мастер</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Услуга</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Начало</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Заметки</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Изменить</p>
            </div>

            {% for appointment in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        #{{ appointment.id }}
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        {{ appointment.client.user.get_full_name }}<br/>
                        <span class="inline-block bg-fuchsia-100 text-fuchsia-800 text-xs font-semibold mr-2 mb-2 px-3 py-1 rounded-full">
                        {{ appointment.client.phone }}
                        </span><br/>
                        <span class="inline-block bg-fuchsia-100 text-fuchsia-800 text-xs font-semibold mr-2 mb-2 px-3 py-1 rounded-full">
                        {{ appointment.client.user.email }}
                        </span>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        {{ appointment.worker.user.get_full_name }}<br/>
                        <span class="inline-block bg-fuchsia-100 text-fuchsia-800 text-xs font-semibold mr-2 mb-2 px-3 py-1 rounded-full">
                        {{ appointment.worker.user.username }}
                        </span>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        {{ appointment.service.name }} <br/>
                        <span class="inline-block bg-fuchsia-100 text-fuchsia-800 text-xs font-semibold mr-2 mb-2 px-3 py-1 rounded-full">
                        {{ appointment.service.price }}₽
                        </span>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <time class="inline-block bg-fuchsia-100 text-fuchsia-800 text-xs font-semibold mr-2 mb-2 px-3 py-1 rounded-full">
                        {{ appointment.start_time }}
                        </time>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ appointment.get_status_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ appointment.notes }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'appointment:update' appointment.id %}" class="inline-block p-2 bg-blue-500 hover:bg-blue-600 text-white rounded-l-full transition duration-200 my-2">
                            <i class="fa fa-pen"></i>
                        </a>
                        <a  href="#" onclick="deleteResource(event, '{% url 'appointment:delete' appointment.id %}', '{{ csrf_token }}')" class="inline-block p-2 bg-red-500 hover:bg-red-600 text-white rounded-r-full transition duration-200 my-2">
                            <i class="fa fa-trash"></i>
                        </a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">Нет {{title}} в базе сейчас...</p>
        {% endif %}
    </div>
{% endblock %}

app/appointment/templates/appointment/review_form.html
{% extends 'core/base.html' %}

{% block content %}
<div class="max-w-2xl mx-auto p-6">
    <h1 class="text-2xl font-bold mb-6">Оставить отзыв</h1>
    
    <!-- Информация о записи -->
    <div class="bg-gray-100 p-4 rounded-lg mb-6">
        <h3 class="font-semibold mb-2">Информация о записи:</h3>
        <p><strong>Специалист:</strong> {{ view.appointment.worker.user.get_full_name }}</p>
        <p><strong>Услуга:</strong> {{ view.appointment.service.name }}</p>
        {% if view.appointment.date %}
        <p><strong>Дата:</strong> {{ view.appointment.date|date:"d.m.Y" }}</p>
        <p><strong>Время:</strong> {{ view.appointment.time|time:"H:i" }}</p>
        {% endif %}
    </div>
    <form method="post" action="{% url 'appointment:review' view.appointment.id %}">
        {% csrf_token %}
        {% for field in form %}
            <div class="mb-4">
                <label class="block text-gray-700 font-medium mb-2">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <p class="text-red-500 text-sm mt-1">{{ field.errors.0 }}</p>
                {% endif %}
            </div>
        {% endfor %}

        <div class="flex gap-4">
            <button type="submit" class="py-3 px-6 bg-green-500 hover:bg-green-600 text-white rounded-lg transition duration-200">
                Отправить отзыв
            </button>
            <a href="{% url 'dashboard:index' %}" class="py-3 px-6 bg-gray-500 hover:bg-gray-600 text-white rounded-lg transition duration-200">
                Отмена
            </a>
        </div>
    </form>
</div>
{% endblock %}