app/beautycrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about, service, OrderView

from profile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/services/', include('service.urls')),
    path('dashboard/appointment/', include('appointment.urls')),
    path('dashboard/payment/', include('payment.urls')),
    path('dashboard/', include('profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('service/', service, name='service'),
    path('order/', OrderView.as_view(), name='order'),
    path('log-in/', views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    # Выплаты
    path('', views.PaymentListView.as_view(), name='list'),
    path('create/', views.PaymentCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.PaymentUpdateView.as_view(), name='update'),
]

app/profile/urls.py
from django.urls import path

from . import views

app_name = 'profile'

urlpatterns = [
    
    # Client
    path('clients/', views.ClientListView.as_view(), name='client_list'),
    path('clients/create/', views.ClientCreateView.as_view(), name='client_create'),
    path('clients/<int:pk>/update/', views.ClientUpdateView.as_view(), name='client_update'),
    path('clients/<int:pk>/delete/', views.ClientDeleteView.as_view(), name='client_delete'),
    
    # Worker
    path('workers/', views.WorkerListView.as_view(), name='worker_list'),
    path('workers/create/', views.WorkerCreateView.as_view(), name='worker_create'),
    path('workers/<int:pk>/update/', views.WorkerUpdateView.as_view(), name='worker_update'),
    path('workers/<int:pk>/delete/', views.WorkerDeleteView.as_view(), name='worker_delete'),
    
    # Position
    path('workers/position/', views.PositionListView.as_view(), name='position_list'),
    path('workers/position/create/', views.PositionCreateView.as_view(), name='position_create'),
    path('workers/position/<int:pk>/update/', views.PositionUpdateView.as_view(), name='position_update'),
    path('workers/position/<int:pk>/delete/', views.PositionDeleteView.as_view(), name='position_delete'),
    
    # Account
    path('myaccount/', views.myaccount, name='myaccount'),
    path('update_myaccount/<int:pk>', views.MyAccountUpdateView.as_view(), name='update_myaccount'),
    path('sign-up/', views.signup, name='signup'),
]

app/profile/models.py
from django.contrib.auth.models import User
from django.db import models

GENDER_CHOICES = [
    ('M', 'Мужской'),
    ('F', 'Женский'),
    ('U', 'Универсал'),
]

class Position(models.Model):
    name = models.CharField(max_length=100, unique=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES, null=True)
    
    def __str__(self):
        return self.name

class BaseProfile(models.Model):
    """Абстрактная базовая модель для профилей"""
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    phone = models.CharField(max_length=20, blank=True)
    address = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    bonuses = models.IntegerField(default=0)

    class Meta:
        abstract = True

class WorkerProfile(BaseProfile):
    """Профиль сотрудника"""
    hire_date = models.DateField()
    is_active = models.BooleanField(default=True)
    position = models.ManyToManyField(Position, blank=True, related_name='workers')
    salary = models.DecimalField(max_digits=10, decimal_places=2, default=0) 
        
    def __str__(self):
        return f"Сотрудник: {self.user.get_full_name()}"

class ClientProfile(BaseProfile):
    """Профиль клиента"""
    notes = models.TextField(blank=True)
    def __str__(self):
        return f"Клиент: {self.user.get_full_name()}"

app/profile/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from utils.profile_helper import get_profile
from .forms import PositionForm, SignupForm, WorkerProfileForm
from .models import ClientProfile, Position, WorkerProfile
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from django.urls import reverse_lazy
from .forms import ClientProfileForm

###
## Client Views
###
class ClientListView(ListView):
    model = ClientProfile
    template_name = 'profile/client_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create'] = 'profile:client_create'
        context['title'] = 'Клиенты'
        
        return context
    
    def get_queryset(self):
        queryset = super(ClientListView, self).get_queryset()
        return queryset.all()

class ClientCreateView(CreateView):
    model = ClientProfile
    form_class = ClientProfileForm
    template_name = 'profile/form.html'
    success_url = reverse_lazy('profile:client_list')
    

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить работника'

        return context

    def form_valid(self, form):
        user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            email=form.cleaned_data['email'],
        )

        ClientProfile.objects.create(
            user=user,
            phone=form.cleaned_data['phone'],
            address=form.cleaned_data['address'],
            notes=form.cleaned_data['notes'],
        )

        return redirect(self.success_url)

    # def form_valid(self, form):
    #     user = User.objects.create_user(
    #         username=form.cleaned_data['username'],
    #         password=form.cleaned_data['password'],
    #         first_name=form.cleaned_data['first_name'],
    #         last_name=form.cleaned_data['last_name'],
    #         email=form.cleaned_data['email'],
    #     )

    #     ClientProfile.objects.create(
    #         user=user,
    #         phone=form.cleaned_data['phone'],
    #         address=form.cleaned_data['address'],
    #         notes=form.cleaned_data['notes'],
    #     )
        
    #     return super().form_valid(form)

class ClientUpdateView(UpdateView):
    model = ClientProfile
    form_class = ClientProfileForm
    template_name = 'profile/form.html'
    success_url = reverse_lazy('profile:client_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактировать клиента'
        return context
    
    def form_valid(self, form):
        # 1. Получаем профиль и связанного пользователя
        profile = form.save(commit=False)
        user = profile.user
        # 2. Обновляем данные пользователя из очищенных данных формы
        if user:
            user.username = form.cleaned_data.get('username', user.username)
            user.first_name = form.cleaned_data.get('first_name', user.first_name)
            user.last_name = form.cleaned_data.get('last_name', user.last_name)
            user.email = form.cleaned_data.get('email', user.email)
        else:
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                # password=form.cleaned_data['new_password'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
            )
            profile.user = user
        
        # Обновляем пароль только если он был предоставлен
        password = form.cleaned_data.get('password')
        if password:
            user.set_password(password)
            
        user.save()
        profile.save()

        from django.contrib import messages
        messages.success(self.request, f'Профиль сотрудника {user.get_full_name()} успешно обновлен')
            
        return redirect(self.get_success_url())

class ClientDeleteView(DeleteView):
    model = ClientProfile
    template_name = 'profile/detail.html'
    success_url = reverse_lazy('profile:client_list')

###
## Worker Views
###
class WorkerListView(ListView):
    model = WorkerProfile
    template_name = 'profile/worker_list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['create'] = 'profile:worker_create'
        context['title'] = 'Работники'
        
        return context
    
    def get_queryset(self):
        queryset = super(WorkerListView, self).get_queryset().select_related('user').prefetch_related('position')
        profiles = queryset.all()
        for profile in profiles:
            print(profile.position.all())
        return profiles

class WorkerCreateView(CreateView):
    model = WorkerProfile
    form_class = WorkerProfileForm
    template_name = 'profile/form.html'
    success_url = reverse_lazy('profile:worker_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить работника'

        return context

    def form_valid(self, form):
        # 1. Создаём пользователя
        user = User.objects.create_user(
            username=form.cleaned_data['username'],
            password=form.cleaned_data['password'],
            first_name=form.cleaned_data['first_name'],
            last_name=form.cleaned_data['last_name'],
            email=form.cleaned_data['email'],
        )

        # 2. Сохраняем профиль без ManyToMany-поля
        profile = WorkerProfile.objects.create(
            user=user,
            hire_date=form.cleaned_data['hire_date'],
            phone=form.cleaned_data['phone'],
            address=form.cleaned_data['address'],
            is_active=True,
        )

        # 3. Назначаем позиции (ManyToMany)
        profile.position.set(form.cleaned_data['position'])

        return super().form_valid(form)

class WorkerUpdateView(UpdateView):
    model = WorkerProfile
    form_class = WorkerProfileForm
    template_name = 'profile/form.html'
    success_url = reverse_lazy('profile:worker_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Редактировать работника'
        # Можно добавить дополнительные данные в контекст
        # context['worker'] = self.get_object()
        return context

    # def get_initial(self):
    #     """Предзаполняем данные из связанного пользователя"""
    #     initial = super().get_initial()
    #     profile = self.get_object()
    #     if profile and profile.user:
    #         user = profile.user
    #         initial.update({
    #             'username': user.username,
    #             'first_name': user.first_name,
    #             'last_name': user.last_name,
    #             'email': user.email,
    #         })
    #     return initial

    def form_valid(self, form):
        # 1. Получаем профиль и связанного пользователя
        profile = form.save(commit=False)
        user = profile.user
        # 2. Обновляем данные пользователя из очищенных данных формы
        if user:
            user.username = form.cleaned_data.get('username', user.username)
            user.first_name = form.cleaned_data.get('first_name', user.first_name)
            user.last_name = form.cleaned_data.get('last_name', user.last_name)
            user.email = form.cleaned_data.get('email', user.email)
        else:
            user = User.objects.create_user(
                username=form.cleaned_data['username'],
                # password=form.cleaned_data['new_password'],
                first_name=form.cleaned_data['first_name'],
                last_name=form.cleaned_data['last_name'],
                email=form.cleaned_data['email'],
            )
            profile.user = user
        
        # Обновляем пароль только если он был предоставлен
        password = form.cleaned_data.get('password')
        if password:
            user.set_password(password)
            
        # Сохраняем изменения пользователя
        user.save()

        # 3. Сохраняем профиль
        profile.save()

        # 4. Обновляем ManyToMany — позиции
        if 'position' in form.cleaned_data:
            profile.position.set(form.cleaned_data['position'])
            
        from django.contrib import messages
        messages.success(self.request, f'Профиль сотрудника {user.get_full_name()} успешно обновлен')
            
        return redirect(self.get_success_url())

class WorkerDeleteView(DeleteView):
    model = WorkerProfile
    template_name = 'profile/detail.html'
    success_url = reverse_lazy('profile:worker_list')

###
## Worker Position
###
class PositionListView(ListView):
    model = Position
    template_name = 'position/list.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Специализации'
        
        return context
    
    def get_queryset(self):
        queryset = super(PositionListView, self).get_queryset()
        return queryset.all()

class PositionCreateView(CreateView):
    model = Position
    form_class = PositionForm
    template_name = 'position/form.html'
    success_url = reverse_lazy('profile:position_list')
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить специализацию'

        return context

    def form_valid(self, form):

app/profile/templates/profile/client_list.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{title}}</h1>

        <a href="{% url create %}" class="inline-block py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Добавить</a>
    
        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Имя</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Телефон</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Заметки</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Добавлен</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Изменить</p>
            </div>

            {% for profile in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        {{ profile.user.first_name }} {{ profile.user.last_name }}
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        {{ profile.phone }}
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ profile.notes }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ profile.created_at }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'profile:client_update' profile.id %}" class="inline-block p-2 bg-blue-500 hover:bg-blue-600 text-white rounded-l-full transition duration-200 my-2">
                            <i class="fa fa-pen"></i>
                        </a>
                        <a  href="#" onclick="deleteResource(event, '{% url 'profile:client_delete' profile.id %}', '{{ csrf_token }}')" class="inline-block p-2 bg-red-500 hover:bg-red-600 text-white rounded-r-full transition duration-200 my-2">
                            <i class="fa fa-trash"></i>
                        </a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">Нет данных для раздела "{{title}}"</p>
        {% endif %}
    </div>
{% endblock %}

app/profile/templates/profile/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">{{ title }}</h1>

        <form method="post" action=".">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-4">
                <label class="block text-gray-700">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <p class="text-red-500 text-sm">{{ field.errors.0 }}</p>
                {% endif %}
                </div>
            {% endfor %}

            <button class="py-4 px-8 bg-fuchsia-500 text-white rounded-xl">Отправить</button>
        </form>
    </div>
{% endblock %}

app/profile/templates/profile/worker_list.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{title}}</h1>

        <a href="{% url create %}" class="inline-block py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Добавить</a>
    
        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Имя</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Дата найма</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Специализации</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Обновлен</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Изменить</p>
            </div>

            {% for profile in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        {{ profile.user.first_name }} {{ profile.user.last_name }}
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ profile.hire_date }}</p>
                        <ul class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                            {% for position in profile.position.all %}
                                <li class="inline-block bg-fuchsia-100 text-fuchsia-800 text-xs font-semibold mr-2 mb-2 px-3 py-1 rounded-full">
                                    {{ position.name }}
                                </li>
                                {% empty %}
                                <li >Нет позиций</li>
                            {% endfor %}
                        </ul>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        {% if profile.is_active %}
                            Работает
                        {% else %}
                            Не работает
                        {% endif %}
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ profile.updated_at }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'profile:worker_update' profile.id %}" class="inline-block p-2 bg-blue-500 hover:bg-blue-600 text-white rounded-l-full transition duration-200 my-2">
                            <i class="fa fa-pen"></i>
                        </a>
                        <a  href="#" onclick="deleteResource(event, '{% url 'profile:worker_delete' profile.id %}', '{{ csrf_token }}')" class="inline-block p-2 bg-red-500 hover:bg-red-600 text-white rounded-r-full transition duration-200 my-2">
                            <i class="fa fa-trash"></i>
                        </a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">Нет данных для раздела "{{title}}"</p>
        {% endif %}
    </div>
{% endblock %}