app/beautycrm/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about, service, OrderView

from profile.forms import LoginForm

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/services/', include('service.urls')),
    path('dashboard/appointment/', include('appointment.urls')),
    path('dashboard/payment/', include('payment.urls')),
    path('dashboard/', include('profile.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('service/', service, name='service'),
    path('order/', OrderView.as_view(), name='order'),
    path('log-in/', views.LoginView.as_view(template_name='account/login.html', authentication_form=LoginForm), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# +static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/payment/urls.py
from django.urls import path

from . import views

app_name = 'payment'

urlpatterns = [
    # Выплаты
    path('', views.PaymentListView.as_view(), name='list'),
    path('create/', views.PaymentCreateView.as_view(), name='create'),
    path('<int:pk>/update/', views.PaymentUpdateView.as_view(), name='update'),
]

app/service/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    # Услуги
    path('', views.ServiceListView.as_view(), name='list'),
    path('create/', views.ServiceCreateView.as_view(), name='create'),
    path('<int:pk>/', views.ServiceDetailView.as_view(), name='detail'),
    path('<int:pk>/update/', views.ServiceUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', views.ServiceDeleteView.as_view(), name='delete'),
    # Категории услуг
    path('category/', views.ServiceCategoryListView.as_view(), name='category_list'),
    path('category/create/', views.ServiceCategoryCreateView.as_view(), name='category_create'),
    path('category/<int:pk>/update/', views.ServiceCategoryUpdateView.as_view(), name='category_update'),
    path('category/<int:pk>/delete/', views.ServiceCategoryDeleteView.as_view(), name='category_delete'),
]

app/appointment/models.py
from django.db import models
from django.utils import timezone

from profile.models import ClientProfile
from profile.models import WorkerProfile
from service.models import Service

# Create your models here.

class Appointment(models.Model):
    STATUS_CHOICES = [
        ('pending', 'Ожидает подтверждения'),
        ('confirmed', 'Подтверждена'),
        ('completed', 'Завершена'),
        ('cancelled', 'Отменена'),
    ]

    client = models.ForeignKey(ClientProfile, on_delete=models.CASCADE, related_name='appointments')
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name='appointments', null=True)
    worker = models.ForeignKey(WorkerProfile, on_delete=models.CASCADE, related_name='appointments', null=True)

    start_time = models.DateTimeField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    notes = models.TextField(blank=True, null=True)

    class Meta:
        ordering = ['-created_at', ]

    def __str__(self):
        return f"{self.client} — {self.service}"


class Review(models.Model):
    RATING_CHOICES = [
        (1, '1 звезда'),
        (2, '2 звезды'),
        (3, '3 звезды'), 
        (4, '4 звезды'),
        (5, '5 звезд'),
    ]

    client = models.ForeignKey(ClientProfile, on_delete=models.CASCADE, related_name='reviews')
    worker = models.ForeignKey(WorkerProfile, on_delete=models.CASCADE, related_name='reviews')
    appointment = models.ForeignKey(Appointment, on_delete=models.CASCADE, related_name='reviews')  # Исправлено: apointment -> appointment
    rating = models.IntegerField(choices=RATING_CHOICES)
    comment = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['client'], name='idx_review_client'),
            models.Index(fields=['worker'], name='idx_review_worker'),
            models.Index(fields=['appointment'], name='idx_review_appointment'),  # Исправлено: appointment
        ]
        # Рекомендуется добавить уникальное ограничение
        unique_together = ['client', 'appointment']

    def __str__(self):
        return f'Отзыв от {self.client} для {self.worker} - {self.rating} звезд'

app/service/models.py
from django.db import models

from profile.models import ClientProfile, WorkerProfile

GENDER_CHOICES = [
    ('M', 'Мужской'),
    ('F', 'Женский'),
    ('U', 'Универсал'),
]

class ServiceCategory(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True, null=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Service(models.Model):
    category = models.ForeignKey(ServiceCategory, on_delete=models.CASCADE, related_name='services')
    name = models.CharField(max_length=255)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES, default='U')
    description = models.TextField(blank=True, null=True)
    duration = models.IntegerField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        indexes = [
            models.Index(fields=['category'], name='idx_service_category'),
        ]

    def __str__(self):
        return self.name
 

app/service/forms.py
from django import forms

from beautycrm.constants import FORMS

from .models import Service, ServiceCategory

class ServiceCategoryForm(forms.ModelForm):
    class Meta:
        model = ServiceCategory
        fields = ('name', 'description', 'is_active',)
        widgets = {
            'name': forms.TextInput(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
            'description': forms.Textarea(attrs={
                'class': FORMS['FIELD_CLASS'],
                'rows': 4
            }),
            'is_active': forms.CheckboxInput(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
        }
        
class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ('category', 'name', 'gender', 'description', 'duration', 'price', 'is_active')
        widgets = {
            'category': forms.Select(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
            'name': forms.TextInput(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
            'gender': forms.Select(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
            'description': forms.Textarea(attrs={
                'class': FORMS['FIELD_CLASS'],
                'rows': 4
            }),
            'duration': forms.NumberInput(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
            'price': forms.NumberInput(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
            'is_active': forms.CheckboxInput(attrs={
                'class': FORMS['FIELD_CLASS'],
            }),
        }

app/service/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
# Create your views here.
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import ListView, DetailView, DeleteView, UpdateView, CreateView

from appointment.models import Appointment

from .forms import ServiceCategoryForm, ServiceForm
from .models import Service, ServiceCategory

class ServiceListView(LoginRequiredMixin, ListView):
    model = Service
    
    def get_queryset(self):
        queryset = super(ServiceListView, self).get_queryset()
        return queryset.all()

class ServiceCreateView(LoginRequiredMixin, CreateView):
    model = Service
    fields = ('category', 'name', 'gender', 'description', 'duration', 'price', 'is_active',)
    success_url = reverse_lazy('services:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        
        context['form'] = ServiceForm()
        context['title'] = 'Добавить услугу'

        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.created_by = self.request.user
        self.object.save()
        
        return redirect(self.get_success_url())
class ServiceDetailView(LoginRequiredMixin, DetailView):
    model = Service
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ServiceForm()
        context['category_form'] = ServiceCategoryForm()

        return context

    def get_queryset(self):
        queryset = super(ServiceDetailView, self).get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))
    
class ServiceDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        category = get_object_or_404(Service, pk=pk)
        # можно добавить проверку доступа
        category.delete()
        return redirect('services:list')

    def get(self, request, *args, **kwargs):
        # запретить или сделать редирект
        return redirect('services:list')

class ServiceUpdateView(LoginRequiredMixin, UpdateView):
    model = Service
    form_class = ServiceForm
    success_url = reverse_lazy('services:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменить услугу'

        return context

    def get_queryset(self):
        queryset = super(ServiceUpdateView, self).get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))

###
## Service category
###
class ServiceCategoryListView(LoginRequiredMixin, ListView):
    model = ServiceCategory
    template_name = 'service/category_list.html'
    success_url = reverse_lazy('services:category_list')
    
    def get_queryset(self, **kwargs):
        queryset = super(ServiceCategoryListView, self).get_queryset()
        return queryset.all()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Категории услуг'
        return context

class ServiceCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ServiceCategory
    form_class = ServiceCategoryForm
    template_name = 'service/category_form.html'
    success_url = reverse_lazy('services:category_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Добавить категорию'
        return context

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.save()
        
        return redirect(self.get_success_url())

class ServiceCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ServiceCategory
    form_class = ServiceCategoryForm
    template_name = 'service/category_form.html'
    success_url = reverse_lazy('services:category_list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Изменить услугу'

        return context

    def get_queryset(self):
        queryset = super(ServiceCategoryUpdateView, self).get_queryset()
        return queryset.filter(pk=self.kwargs.get('pk'))
    
# class ServiceCategoryDeleteView(LoginRequiredMixin, DeleteView):
#     model = ServiceCategory
#     success_url = reverse_lazy('services:category_list')

#     def get_queryset(self):
#         queryset = super().get_queryset()
#         return queryset.filter(pk=self.kwargs.get('pk'))

class ServiceCategoryDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        print(pk)
        category = get_object_or_404(ServiceCategory, pk=pk)
        # можно добавить проверку доступа
        category.delete()
        return redirect('services:category_list')

    def get(self, request, *args, **kwargs):
        # запретить или сделать редирект
        return redirect('services:category_list')

app/service/templates/service/category_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">{{ title }}</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-4">
                <label class="block text-gray-700">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <p class="text-red-500 text-sm">{{ field.errors.0 }}</p>
                {% endif %}
                </div>
            {% endfor %}

            <button class="py-4 px-8 bg-fuchsia-500 text-white rounded-xl">Отправить</button>
        </form>
    </div>
{% endblock %}

app/service/templates/service/category_list.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{title}}</h1>

        <a href="{% url 'services:category_create' %}" class="inline-block py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Добавить</a>
    
        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Имя</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Приоритет</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Изменить</p>
            </div>

            {% for category in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'services:category_update' category.id %}">
                            {{ category.name }}
                        </a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ category.description }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ category.is_active }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'services:category_update' category.id %}" class="inline-block p-2 bg-blue-500 hover:bg-blue-600 text-white rounded-l-full transition duration-200 my-2">
                            <i class="fa fa-pen"></i>
                        </a>
                        <a  href="#" onclick="deleteResource(event, '{% url 'services:category_delete' category.id %}', '{{ csrf_token }}')" class="inline-block p-2 bg-red-500 hover:bg-red-600 text-white rounded-r-full transition duration-200 my-2">
                            <i class="fa fa-trash"></i>
                        </a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">Нет данных для раздела "{{title}}"</p>
        {% endif %}
    </div>
{% endblock %}

app/service/templates/service/service_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ service.name }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{ service.name }}</h1>

        {% if service.description %}
            <p class="font-semibold">Name</p>
            <p class="mb-2">{{ service.description }}</p>
        {% endif %}

        <p class="font-semibold">Priority</p>
        <p class="mb-2">{{ service.get_priority_display }}</p>

        <p class="font-semibold">Status</p>
        <p class="mb-2">{{ service.get_status_display }}</p>

        <p class="font-semibold">Created at</p>
        <p class="mb-2">{{ service.created_at }}</p>

        <p class="font-semibold">Modifed at</p>
        <p class="mb-6">{{ service.modified_at }}</p>

        <hr class="my-4">

        <form id="service_delete_form" method="post" action="{% url 'services:delete' service.id %}">
            {% csrf_token %}
        </form>

        <a href="{% url 'services:convert' service.id %}" class="py-2 px-4 rounded-xl bg-blue-500 text-white">Convert to client</a>
        <a href="{% url 'services:edit' service.id %}" class="py-2 px-4 rounded-xl bg-fuchsia-500 text-white">Edit</a>
        <a href="#" onclick="document.getElementById('service_delete_form').submit();" class="py-2 px-4 rounded-xl bg-red-500 text-white">Delete</a>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Услуги</h2>

        <div class="space-y-4">
            {% for comment in service.comments.all %}
                <div class="bg-gray-100 p-6 rounded-xl">
                    <p class="mb-2"><strong>{{ comment.created_by }}</strong> @ {{ comment.created_at }}</p>
                    
                    {{ comment.content }}
                </div>
            {% endfor %}
        </div>

        <form method="post" action="{% url 'services:add_comment' service.id %}">
            {% csrf_token %}

            {{ form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Отправить</button>
        </form>

        <hr class="my-4">

        <h2 class="mb-6 text-xl">Категории услуг</h2>

        <form method="post" action="{% url 'services:add_file' service.id %}" enctype="multipart/form-data">
            {% csrf_token %}

            {{ category_form.as_p }}

            <button class="py-2 px-4 rounded-xl bg-blue-500 text-white">Submit</button>
        </form>

        <hr class="my-4">

        <a href="{% url 'services:list' %}">Обратно к услугам</a>
    </div>
{% endblock %}

app/service/templates/service/service_form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="text-xl">{{ title }}</h1>

        <form method="post" action=".">
            {% csrf_token %}

            {% for field in form %}
                <div class="mb-4">
                <label class="block text-gray-700">{{ field.label }}</label>
                {{ field }}
                {% if field.errors %}
                    <p class="text-red-500 text-sm">{{ field.errors.0 }}</p>
                {% endif %}
                </div>
            {% endfor %}

            <button class="py-4 px-8 bg-fuchsia-500 text-white rounded-xl">Отправить</button>
        </form>
    </div>
{% endblock %}

app/service/templates/service/service_list.html
{% extends 'core/base.html' %}

{% block title %}{{title}}{% endblock %}

{% block content %}
    <div class="py-6 px-6">
        <h1 class="mb-4 text-xl">{{title}}</h1>

        <a href="{% url 'services:create' %}" class="inline-block py-4 px-6 bg-fuchsia-600 rounded-xl text-white">Добавить</a>
    
        {% if object_list %}
            <div class="mt-6 flex justify-between">
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Имя</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Категория</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Гендер</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Описание</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Продолжит. (мин.)</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Цена</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Статус</p>
                <p class="py-4 px-2 bg-gray-200 font-semibold w-full">Изменить</p>
            </div>

            {% for service in object_list %}
                <div class="flex justify-between">
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'services:detail' service.id %}">{{ service.name }}</a>
                    </p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ service.category }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ service.get_gender_display }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ service.description }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ service.duration }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ service.price }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">{{ service.is_active }}</p>
                    <p class="py-2 px-2 w-full {% cycle 'bg-gray-100' '' %}">
                        <a href="{% url 'services:update' service.id %}" class="inline-block p-2 bg-blue-500 hover:bg-blue-600 text-white rounded-l-full transition duration-200 my-2">
                            <i class="fa fa-pen"></i>
                        </a>
                        <a  href="#" onclick="deleteResource(event, '{% url 'services:delete' service.id %}', '{{ csrf_token }}')" class="inline-block p-2 bg-red-500 hover:bg-red-600 text-white rounded-r-full transition duration-200 my-2">
                            <i class="fa fa-trash"></i>
                        </a>
                    </p>
                </div>
            {% endfor %}
        {% else %}
            <p class="mt-6 px-2">Нет {{title}} в базе сейчас...</p>
        {% endif %}
    </div>
{% endblock %}